name: Build and Publish PDFs

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build PDFs with Docker
        run: |
          docker run --rm -v $(pwd):/mnt aergus/latex:latest \
            bash -c "cd /mnt/books && for book_folder in *; do if [ -d \$book_folder ]; then cd \$book_folder && latexmk -pdf -interaction=nonstopmode book.tex && cd ..; fi; done"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
            files: books/*/book.pdf
            token: ${{ secrets.GITHUB_TOKEN }}
            tag_name: ${{ github.run_number }}
            release_name: Release ${{ github.run_number }}
            body: |
                This is an automated release of PDFs.
            draft: false
            prerelease: false

      - name: Upload PDFs
        uses: actions/upload-artifact@v2
        with:
          name: pdf-artifacts
          path: books/*/book.pdf

      - name: Attach PDFs to Release
        id: attach_pdf
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: books/*/book.pdf
          asset_name: book.pdf
          asset_content_type: application/pdf
